export const lista_prodoktow = [
    {
        id: 244925,
        nazwa: "Klapki Ripndip Lord Nermal Slides",
        opis: '',
        opisPunkty: [
            {punkt: "Klapki Ripndip,"},
            {punkt: "Model wykonany z materiałów syntetycznych,"},
            {punkt: "Anatomiczny profil zapewnia komfort i doskonałe dopasowanie do kształtu stopy,"},
            {punkt: "Podeszwa z antypoślizgowym bieżnikiem gwarantuje stabilność i bardzo dobrą przyczepność,"},
            {punkt: "Kolor: Purple Camo"}
        ],
        cena: "179,00 zł",
        rozmiary: ["41", "42", "43", "44"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244925-a77152.jpg",
        kategoriaId: 1,
        podkategoriaId: 1
    },
    {
        id: 188755,
        nazwa: "Buty Vans Old Skool Pro",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał wierzchni: skóra (zamsz), materiał włókienniczy,"},
            {punkt: "Wyściółka: materiał włókienniczy,"},
            {punkt: "Podeszwa: tworzywo sztuczne,"},
            {punkt: "Wkładka ULTRA CUSH HD - chroniąca stopę przed silnymi uderzeniami,"},
            {punkt: "Klasyczne tenisówki, lekkie i wygodne,"},
            {punkt: "System WAFFLE GRIP dla lepszej przyczepności,"},
            {punkt: "Dodatkowa para sznurówek w komplecie,"},
            {punkt: "Kontrastowe elementy i stylowe detale wykończenia,"},
            {punkt: "Kolekcja VANS CLASSIC!!!"},
            {punkt: "kod: 00ZD4Y28"}
        ],
        cena: "269,00 zł",
        rozmiary: ["36.5", "37", "38", "38.5", "39", "40", "40.5", "41", "42", "42.5", "43", "44", '45.5'],
        bestseller: true,
        obrazek: "https://csts3.quartic.com.pl/e8a2d2ff4a3b47e2/e1-c0/230x345/aHR0cDovL3NlbGVjdHNob3AucGwvbW9k/cHViL19yc2VsZWN0c2hvcC9wcm9kdWN0/L3NtYWxsLzAzMjAxOC8xODg3NTUtOTg0/YmZlLmpwZw==.jpg",
        kategoriaId: 1,
        podkategoriaId: 2
    },
    {
        id: 244731,
        nazwa: "Buty Nike SB Zoom Stefan Janoski Canvas RM Premium",
        opis: "Nike SB Zoom Janoski Canvas Premium RM łączą minimalistyczny wygląd z nowoczesnym dopasowaniem. Dzięki nowej, miękkiej wkładce i elastycznej podeszwie środkowej buty od samego początku zapewniają lepsze czucie deski.",
        opisPunkty: [
            {punkt: "Materiał: wytrzymały materiał tekstylny,"},
            {punkt: "Wyściółka: materiał tekstylny,"},
            {punkt: "Podeszwa: guma wulkanizowana,"},
            {punkt: "Lekkie i solidne,"},
            {punkt: "Moduł Zoom Air we wkładce zapewnia dynamiczną amortyzację,"},
            {punkt: "Sygnowane przez Stefana Janoskiego,"},
            {punkt: "Podwójnie szyte noski,"},
            {punkt: "Na nosku otwory wentylacyjne,"},
            {punkt: "Metalowe okucia na sznurowadła,"},
            {punkt: "Kolor: BLACK/BLACK-BLACK-LASER CRIMSON"},
            {punkt: "Kod produktu: AQ7878"},
            {punkt: "Najnowsza Kolekcja!!!"}
        ],
        cena: "299,00 zł",
        rozmiary: ["38.5", "42.5", "44"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244731-ddf332.jpg",
        kategoriaId: 1,
        podkategoriaId: 2
    },
    {
        id: 244730,
        nazwa: "Buty Nike SB Zoom Stefan Janoski Slip RM",
        opis: "Nike SB Zoom Janoski Slip RM to klasyczny but w ulepszonym wydaniu. Buty łączą minimalistyczny wygląd i nowoczesny krój. Dzięki nowej, miękkiej wkładce i elastycznej podeszwie środkowej buty od samego początku zapewniają lepsze czucie deski.",
        opisPunkty: [
            {punkt: "Materiał wierzchni: skóra-zamsz,"},
            {punkt: "Wyściółka: materiał tekstylny,"},
            {punkt: "Posiadają wkładkę Zoom Air, dla lepszego czucia deski,"},
            {punkt: "Podeszwa: guma wulkanizowana,"},
            {punkt: "Po obu stronach buta haftowane loga Nike,"},
            {punkt: "Klasyczne, wsuwane buty,"},
            {punkt: "Kod produktu: AT8899-100"},
            {punkt: "Kolor: SUMMIT WHITE/UNIVERSITY GOLD"},
            {punkt: "Sygnowane: Stefan Janoski."}
        ],
        cena: "279,00 zł",
        rozmiary: ["38", "38.5", "39", "40", "41", "42", "42.5", "43", "44", "45"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244730-88df15.jpg",
        kategoriaId: 1,
        podkategoriaId: 2
    },
    {
        id: 241873,
        nazwa: "Buty Nike SB Zoom Dunk High Pro",
        opis: "Nike Skateboarding wypuszcza dwia modele SB Dunk w pakiecie „Truck It”, która jest hołdem dla podróży po drogach jednocześnie wyróżniając się stylem lat 70. Model Nike SB Dunk High Pro łączy klasyczny styl butów Dunk z nowoczesnym wzorem z wysoką cholewką. Poduszka gazowa Zoom Air pod piętą i wyściełany język oferują wygodne dopasowanie idealne do jazdy na desce.",
        opisPunkty: [
            {punkt: "Materiał wierzchni: zamsz"},
            {punkt: "Podeszwa: wytrzymała guma z bieżnikiem zapewniającym bardzo dobrą przyczepność,"},
            {punkt: "Kolor: Czerń / Nasycony pomarańczowy /  Intensywna czerwień / Jasne matowe złoto"},
            {punkt: "Komfortowa wkładka wewnętrzna,"},
            {punkt: "Podwójne szycia cholewki,"},
            {punkt: "Po obu stronach buta logo Nike,"},
            {punkt: "Lekko gąbkowany kołnierz,"},
            {punkt: "Kod produktu: BQ6826-003,"},
            {punkt: "Cholewka z zamszu zapewnia wsparcie i wytrzymałość,"},
            {punkt: "Poduszka gazowa Nike Zoom Air pod piętą gwarantuje dynamiczną amortyzację i ochronę przed wstrząsami,"},
            {punkt: "Dodatkowa para sznurówek w komplecie,"},
            {punkt: "Tradycyjna wulkanizowana konstrukcja daje uczucie wyjątkowej bliskości podłoża,"},
            {punkt: "Wytrzymała gumowa podeszwa zewnętrzna z bieżnikiem gwarantuje doskonałą przyczepność."}
        ],
        cena: "379,00 zł",
        rozmiary: ["40.5", "41", "42.5", "43", "44", "44.5", "45.5"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/022020/241873-927044.jpg",
        kategoriaId: 1,
        podkategoriaId: 3
    },
    {
        id: 230147,
        nazwa: "Koszulka Kamuflage Yin Yang",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 100% bawełna,"},
            {punkt: "Możliwość regulacji obwodu kaptura przy pomocy sznurka,"},
            {punkt: "Kolor: Czarny / Biały"},
            {punkt: "Na piersi wysokiej jakości ręcznie robiony nadruk,"},
            {punkt: "Modelka ma 170 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "Rozmiarówka: Unisex,"}
        ],
        cena: "99,00 zł",
        rozmiary: ["XS", "S", "M", "L", "XL"],
        bestseller: true,
        obrazek: "https://csts3.quartic.com.pl/e8a2d2ff4a3b47e2/e1-c0/230x345/aHR0cDovL3NlbGVjdHNob3AucGwvbW9k/cHViL19yc2VsZWN0c2hvcC9wcm9kdWN0/L3NtYWxsLzA1MjAxOS8yMzAxNDctM2M3/MTRhLmpwZw==.jpg",
        kategoriaId: 2,
        podkategoriaId: 4
    },
    {
        id: 245011,
        nazwa: "Koszulka Kamuflage Retro",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 100% bawełna,"},
            {punkt: "Kolor: Biały,"},
            {punkt: "Na przodzie nadruk,"},
            {punkt: "Prosty i wygodny krój,"},
            {punkt: "Zaokrąglone wykończenie kołnierzyka,"},
            {punkt: "Najnowsza kolekcja!"},
            {punkt: "Rozmiarówka: unisex"}
        ],
        cena: "99,00 zł",
        rozmiary: ["XS", "S", "M", "L", "XL"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/245011-ad88e0.jpg",
        kategoriaId: 2,
        podkategoriaId: 4
    },
    {
        id: 245010,
        nazwa: "Koszulka Kamuflage Retro",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 100% bawełna,"},
            {punkt: "Kolor: Czarny,"},
            {punkt: "Na przodzie nadruk,"},
            {punkt: "Prosty i wygodny krój,"},
            {punkt: "Zaokrąglone wykończenie kołnierzyka,"},
            {punkt: "Najnowsza kolekcja!"},
            {punkt: "Rozmiarówka: unisex"}
        ],
        cena: "99,00 zł",
        rozmiary: ["XS", "S", "M", "L", "XL"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/245010-011fc7.jpg",
        kategoriaId: 2,
        podkategoriaId: 4
    },
    {
        id: 244956,
        nazwa: "Koszulka Ripndip Hiker Nerm",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 100% bawełna,"},
            {punkt: "Kolor: Mint"},
            {punkt: "Zaokrąglony kołnierz,"},
            {punkt: "Na przodzie oraz tyle wysokiej jakości nadruki,"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "Wysokiej jakości wykonanie,"},
            {punkt: "Kod: RND4194"}
        ],
        cena: "149,00 zł",
        rozmiary: ["S", "M", "L", "XL"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/244956-252040.jpg",
        kategoriaId: 2,
        podkategoriaId: 4
    },
    {
        id: 230182,
        nazwa: "Koszulka Mass Denim Line Tank",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 100% bawełna,"},
            {punkt: "Prosty, wygodny krój,"},
            {punkt: "Na przodzie ozdobna taśma"},
            {punkt: "Kolor: Blue"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "Krój: Tank Top,"}
        ],
        cena: "49,00 zł",
        rozmiary: ["XL"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/052019/230182-3ebdce.jpg",
        kategoriaId: 2,
        podkategoriaId: 5
    },
    {
        id: 244891,
        nazwa: "Koszula Ripndip Daisy Daze Button Up",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 100% bawełna,"},
            {punkt: "Zapinana na guziki,"},
            {punkt: "Na całej powierzchni nadruki,"},
            {punkt: "Koszula z krótkim rękawkiem,"},
            {punkt: "Kolor: Pink"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "Kod: RND4114"}
        ],
        cena: "299,00 zł",
        rozmiary: ["S", "M", "L"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/244891-b1df38.jpg",
        kategoriaId: 3,
        podkategoriaId: 0
    },
    {
        id: 244890,
        nazwa: "Koszula Ripndip Hold Me Button Up",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał wierzchni: 100% poliester,"},
            {punkt: "Zapinana na guziki,"},
            {punkt: "Na tyle nadruk,"},
            {punkt: "Koszula z krótkim rękawkiem,"},
            {punkt: "Kolor: Blue"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "Kod: rnd4113"},
            {punkt: "Najnowsza kolekcja"}
        ],
        cena: "299,00 zł",
        rozmiary: ["M", "L"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/244890-98250d.jpg",
        kategoriaId: 3,
        podkategoriaId: 0
    },
    {
        id: 242662,
        nazwa: "Koszula Kamuflage Too Many Logos",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 80% bawełna, 20% poliester"},
            {punkt: "Zapinana na guziki,"},
            {punkt: "Prosty i wygodny krój,"},
            {punkt: "Nadruki na całej powierzchni,"},
            {punkt: "Kolor: Czarny"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"}
        ],
        cena: "139,00 zł",
        rozmiary: ["S", "M", "L", "XL"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/022020/242662-da5790.jpg",
        kategoriaId: 3,
        podkategoriaId: 0
    },
    {
        id: 220427,
        nazwa: "Koszula Levis Skateboarding Quilted Mason",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 100% bawełna"},
            {punkt: "Zapinana na guziki,"},
            {punkt: "Prosty krój"},
            {punkt: "Koszula ocieplona idealna na chłodniejsze wieczory,"},
            {punkt: "Na przodzie zapinana kieszeń"},
            {punkt: "Rozpinane mankiety"},
            {punkt: "Kolor: White / Black"},
            {punkt: "Kod producenta: 35891-0001"},
            {punkt: "Model ma 175 cm wzrostu i ma na sobie rozmiar M,"}
        ],
        cena: "449,00 zł",
        rozmiary: ["M"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/102018/220427-ad159f.jpg",
        kategoriaId: 3,
        podkategoriaId: 0
    },
    {
        id: 245014,
        nazwa: "Bluza Kaptur Diil Laur 3D Logo",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 90% bawełna, 10% poliester,"},
            {punkt: "Możliwość regulacji obwodu kaptura przy pomocy sznurka,"},
            {punkt: "Z przodu bluzy nadruk 3D,"},
            {punkt: "Kolor: Grey"},
            {punkt: "Kieszeń kangurka na przodzie,"},
            {punkt: "Na przodzie gumowa aplikacja,"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"}
        ],
        cena: "219,00 zł",
        rozmiary: ["XXL", "XXXL"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/245014-68fff0.jpg",
        kategoriaId: 4,
        podkategoriaId: 6
    },
    {
        id: 245013,
        nazwa: "Bluza Kaptur Biuro Ochrony Rapu Classic B",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 80% bawełna, 20% poliester,"},
            {punkt: "Prosty i wygodny krój,"},
            {punkt: "Na przodzie bluzy nadruk,"},
            {punkt: "Na rękawach elastyczne ściągacze,"},
            {punkt: "Kolor: violet,"},
            {punkt: "Wysoka jakość wykonania,"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"}
        ],
        cena: "199,00 zł",
        rozmiary: ["S", "M", "L"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/245013-765b70.jpg",
        kategoriaId: 4,
        podkategoriaId: 6
    },
    {
        id: 245012,
        nazwa: "Bluza Kaptur Biuro Ochrony Rapu Box",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 80% bawełna, 20% poliester,"},
            {punkt: "Prosty i wygodny krój,"},
            {punkt: "Na przodzie bluzy nadruk,"},
            {punkt: "Na rękawach elastyczne ściągacze,"},
            {punkt: "Kolor: maroon,"},
            {punkt: "Wysoka jakość wykonania,"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"}
        ],
        cena: "199,00 zł",
        rozmiary: ["S", "M", "L", "XL", "XXL"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/245012-b45ddf.jpg",
        kategoriaId: 4,
        podkategoriaId: 6
    },
    {
        id: 244932,
        nazwa: "Bluza Fila Baker",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 65% bawełna, 35% poliester"},
            {punkt: "Na piersi wysokiej nadruk z logo,"},
            {punkt: "Elastyczne ściągacze na spodzie na rękawach bluzy,"},
            {punkt: "Dekoracyjne wstawki niebiesko czerwonych materiałów,"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "Kolor: White"},
            {punkt: "Najnowsza męska kolekcja!"},
            {punkt: "Kod: 687481-A459"}
        ],
        cena: "199,00 zł",
        rozmiary: ["S", "M", "L"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244932-4bdeb8.jpg",
        kategoriaId: 4,
        podkategoriaId: 7
    },
    {
        id: 244924,
        nazwa: "Bluza Zip Ripndip D.N.A. Brushed Fleece 3/4 Zip",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 100% bawełna,"},
            {punkt: "Dwie kieszenie na przodzie,"},
            {punkt: "Zasuwana na zamek 3/4"},
            {punkt: "Nadruki na przodzie i tyle,"},
            {punkt: "Kolor: Black"},
            {punkt: "Gumowa aplikacja na przodzie,"},
            {punkt: "Haft na tyle oraz rękawie,"},
            {punkt: "Elastyczne ściągacze na spodzie i na rękawach,"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "Kod: RND4102"}
        ],
        cena: "199,00 zł",
        rozmiary: ["M", "L"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/244924-68be18.jpg",
        kategoriaId: 4,
        podkategoriaId: 8
    },
    {
        id: 244936,
        nazwa: "Kurtka Zimowa Champion Qulied",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał zewnętrzny: 100% poliamid"},
            {punkt: "Podszewka: 100% poliamid"},
            {punkt: "Elastyczne ściągacze na rękawach i na spodzie,"},
            {punkt: "Na przodzie dwie kieszenie zamykane na zamek błyskawiczny,"},
            {punkt: "Na kołnierzu nadruk,"},
            {punkt: "Zasuwana na zamek,"},
            {punkt: "Możliwość ukrycia kaptura w kołnierzu,"},
            {punkt: "Dupont Sorona: wytrzymały, oddychający oraz lekki materiał"},
            {punkt: "Kurtka pikowana, bardzo lekka i ciepła,"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "Kolor: black/navy"},
            {punkt: "Kod: 213626 KK001"}
        ],
        cena: "399,00 zł",
        rozmiary: ["M", "L", "XL"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/244936-4c985b.jpg",
        kategoriaId: 5,
        podkategoriaId: 9
    },
    {
        id: 244889,
        nazwa: "Kurtka Ripndip Nermhog",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał wierzchni: 100% poliester"},
            {punkt: "Zapinana na napy,"},
            {punkt: "Dwie kieszenie na przodzie,"},
            {punkt: "Kolorowa podszewka,"},
            {punkt: "Na przodzie, tyle oraz rękawie nadruki,"},
            {punkt: "Kolor: Black"},
            {punkt: "Kod: RND4107"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"}
        ],
        cena: "439,00 zł",
        rozmiary: ["L"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/244889-89c927.jpg",
        kategoriaId: 5,
        podkategoriaId: 10
    },
    {
        id: 244888,
        nazwa: "Kurtka Ripndip Ripple Brushed Fleece Half Zip",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał wierzchni: 100% bawełna"},
            {punkt: "Zasuwana na zamek do połowy,"},
            {punkt: "Jedna kieszeń zapinana na zamek na przodzie,"},
            {punkt: "Nadruki na całej powierzchni,"},
            {punkt: "Na przodzie gumowe logo marki,"},
            {punkt: "Kolor: Multicolor"},
            {punkt: "Kod: RND4106"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "Najnowsza kolekcja!"}
        ],
        cena: "539,00 zł",
        rozmiary: ["M", "L"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/244888-2f3654.jpg",
        kategoriaId: 5,
        podkategoriaId: 10
    },
    {
        id: 244887,
        nazwa: "Kurtka Ripndip Prisma Military",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał wierzchni: 100% bawełna"},
            {punkt: "Zapinana na guziki,"},
            {punkt: "Cztery kieszenie na przodzie zasuwane na zamek"},
            {punkt: "Pikowana kolorowa podszewka,"},
            {punkt: "Na tyle haft,"},
            {punkt: "Kolor: Multi"},
            {punkt: "Kod: RND3901"},
            {punkt: "Najnowsza kolekcja!"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"}
        ],
        cena: "539,00 zł",
        rozmiary: ["M", "L"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/244887-84177e.jpg",
        kategoriaId: 5,
        podkategoriaId: 10
    },
    {
        id: 244886,
        nazwa: "Kurtka Ripndip Ignite Sherpa",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał wierzchni: 100% bawełna"},
            {punkt: "Zasuwana na zamek,"},
            {punkt: "Pikowana podszewka,"},
            {punkt: "Dwie kieszenie na przodzie,"},
            {punkt: "Na tyle oraz przodzie haft,"},
            {punkt: "Kolor:Black"},
            {punkt: "Kod: RND4103"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "Najnowsza kolekcja!"}
        ],
        cena: "589,00 zł",
        rozmiary: ["M"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/244886-c0c308.jpg",
        kategoriaId: 5,
        podkategoriaId: 10
    },
    {
        id: 244859,
        nazwa: "Szorty Damskie Kappa Goodje",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 20% poliester, 80% bawełna,"},
            {punkt: "Zapięcie: w pasie ściągnięte elastyczną gumą i regulowane sznurówką,"},
            {punkt: "Dwie kieszonki po bokach,"},
            {punkt: "Dekoracyjne taśmy po bokach z logotypami,"},
            {punkt: "Z przodu haftowane logo,"},
            {punkt: "Kolor: Caviar,"},
            {punkt: "Kod: 307068-4006,"},
            {punkt: "Najnowsza damska kolekcja !!!"}
        ],
        cena: "79,00 zł",
        rozmiary: ["XS", "S", "M"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244859-b49710.jpg",
        kategoriaId: 6,
        podkategoriaId: 11
    },
    {
        id: 244858,
        nazwa: "Szorty Damskie Kappa Galla",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 50% poliester, 50% bawełna,"},
            {punkt: "Zapięcie: w pasie ściągnięte wysoce elastyczną, dekoracyjną gumą,"},
            {punkt: "Dwie kieszonki po bokach,"},
            {punkt: "Z przodu haftowane logo,"},
            {punkt: "Kolor: Caviar,"},
            {punkt: "Kod: 307003-4006,"},
            {punkt: "Najnowsza damska kolekcja !!!"}
        ],
        cena: "139,00 zł",
        rozmiary: ["XS", "S"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244858-385a4b.jpg",
        kategoriaId: 6,
        podkategoriaId: 11
    },
    {
        id: 244854,
        nazwa: "Szorty Ellesse Sidney",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 80% bawełna, 20% poliester,"},
            {punkt: "Po bokach dwie otwarte kieszenie,"},
            {punkt: "Na przodzie naszywki z logotypami,"},
            {punkt: "Na tyle kieszeń zamykana na rzep,"},
            {punkt: "Wysoka jakość wykonania,"},
            {punkt: "Kolor: Light Grey,"},
            {punkt: "Krój: regularny,"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "Najnowsza Kolekcja!!!"},
            {punkt: "Kod: SHC07443GREYMARL"}
        ],
        cena: "99,00 zł",
        rozmiary: ["S", "M", "L"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244854-448367.jpg",
        kategoriaId: 6,
        podkategoriaId: 11
    },
    {
        id: 244795,
        nazwa: "Szorty Columbia Riptide",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: Nylon / Poliester"},
            {punkt: "Po bokach dwie siateczkowe kieszenie zasuwane na zamek,"},
            {punkt: "Wysoka jakość wykonania,"},
            {punkt: "Technologia Omni-Shield® stanowi barierę zarówno dla wody, jak i dla zanieczyszczeń, pozwalając dłużej cieszyć się czystymi rzeczami."},
            {punkt: "Możliwość spakowania szortów do ich własnej tylnej kieszeni,"},
            {punkt: "Krój: regularny,"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "Najnowsza Kolekcja!!!"},
            {punkt: "Kolor: White"},
            {punkt: "Kod: 1889843100"}
        ],
        cena: "169,00 zł",
        rozmiary: ["M", "L"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244795-e89e8a.jpg",
        kategoriaId: 6,
        podkategoriaId: 12
    },
    {
        id: 244679,
        nazwa: "Szorty Prosto Direct",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 98% bawełna, 2% elastan,"},
            {punkt: "Po bokach trzy kieszenie w tym jedna na monety,"},
            {punkt: "Na tyle dwie kieszonki,"},
            {punkt: "Na nogawce haft,"},
            {punkt: "Wysoka jakość wykonania,"},
            {punkt: "Kolor: Blue"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "Krój Regular"},
            {punkt: "Kod: 8806"}
        ],
        cena: "139,00 zł",
        rozmiary: ["S", "M", "L", "XL", "XXL"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244679-ddac42.jpg",
        kategoriaId: 6,
        podkategoriaId: 13
    },
    {
        id: 245231,
        nazwa: "Spodnie Malita Chino Lose",
        opis: '',
        opisPunkty: [
            {punkt: "Tkanina 97% bawełna, 3% lycra"},
            {punkt: "Elastyczne ściągacze w pasie oraz na nogawkach,"},
            {punkt: "Z przodu dwie otwarte kieszenie,"},
            {punkt: "Z tyłu dwie kieszenie,"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "żakardowa metka z logo MALITA nad tylną kieszenią"},
            {punkt: "mała metka Malita na nogawce"},
            {punkt: "mała metka żakardowa z logo M przy wlocie przedniej kieszeni"},
            {punkt: "Kod: 20300"},
            {punkt: "Kolor: Grafit"},
            {punkt: "Najnowsza Kolekcja!!"}
        ],
        cena: "189,00 zł",
        rozmiary: ["XS", "S", "M", "L", "XL", "XXL"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/245231-2dc6e1.jpg",
        kategoriaId: 7,
        podkategoriaId: 14
    },
    {
        id: 245228,
        nazwa: "Spodnie Malita Chino Lose",
        opis: '',
        opisPunkty: [
            {punkt: "Tkanina 97% bawełna, 3% lycra"},
            {punkt: "Elastyczne ściągacze w pasie oraz na nogawkach,"},
            {punkt: "Z przodu dwie otwarte kieszenie,"},
            {punkt: "Z tyłu dwie kieszenie,"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "żakardowa metka z logo MALITA nad tylną kieszenią"},
            {punkt: "mała metka Malita na nogawce"},
            {punkt: "mała metka żakardowa z logo M przy wlocie przedniej kieszeni"},
            {punkt: "Kod: 20301"},
            {punkt: "Kolor: Olive"},
            {punkt: "Najnowsza Kolekcja!!"}
        ],
        cena: "189,00 zł",
        rozmiary: ["XS", "S", "M", "L", "XL", "XXL"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/245228-f94e07.jpg",
        kategoriaId: 7,
        podkategoriaId: 14
    },
    {
        id: 245020,
        nazwa: "Spodnie Metoda Sport Mini MH Jeans",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał 100% bawełna,"},
            {punkt: "Z przodu dwie kieszenie boczne,"},
            {punkt: "Z tyłu dwie kieszenie,"},
            {punkt: "Na tylnej kieszeni mała skórzana naszywka,"},
            {punkt: "Krój: Jogger Fit,"},
            {punkt: "Kolor: Medium Blue"},
            {punkt: "Ściągacze na spodzie spodni,"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"}
        ],
        cena: "159,00 zł",
        rozmiary: ["S", "M", "L", "XL", "XXL", "XXXL"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/245020-0e03a9.jpg",
        kategoriaId: 7,
        podkategoriaId: 15
    },
    {
        id: 245019,
        nazwa: "Spodnie Metoda Sport Mini MH Jeans",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał 100% bawełna,"},
            {punkt: "Z przodu dwie kieszenie boczne,"},
            {punkt: "Z tyłu dwie kieszenie,"},
            {punkt: "Na tylnej kieszeni mała skórzana naszywka,"},
            {punkt: "Krój: Jogger Fit,"},
            {punkt: "Kolor: Dark Jeans"},
            {punkt: "Ściągacze na spodzie spodni,"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"}
        ],
        cena: "159,00 zł",
        rozmiary: ["S", "M", "L", "XL", "XXL", "XXXL"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/245019-a41f42.jpg",
        kategoriaId: 7,
        podkategoriaId: 15
    },
    {
        id: 244690,
        nazwa: "Spodnie Prosto Speed",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał 80% bawełna, 20% poliester,"},
            {punkt: "Elastyczne ściągacze na spodzie nogawek."},
            {punkt: "W pasie guma i sznurek do regulacji."},
            {punkt: "Po bokach dwie kieszenie,"},
            {punkt: "Na tyle kieszonka,"},
            {punkt: "Na lewej nogawce na spodzie wstawki z szaro białego materiału oraz nadruk z logotypem,"},
            {punkt: "Krój typu: Regular Fit,"},
            {punkt: "Kolor: black,"},
            {punkt: "Model ma 183 cm wzrostu i ma na sobie rozmiar M,"},
            {punkt: "Kod: 8841"}
        ],
        cena: "169,00 zł",
        rozmiary: ["S", "M", "L"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244690-516d18.jpg",
        kategoriaId: 7,
        podkategoriaId: 16
    },
    {
        id: 245033,
        nazwa: "Kapelusz The North Face Sun Stash",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 100% Poliester,"},
            {punkt: "Nadruk na przodzie kapleusza,"},
            {punkt: "Kod: NF00CGZ0M1B1"},
            {punkt: "Kapelusz dwustronny,"},
            {punkt: "Możliwość spakowania kapelusza do jego własnej kieszonki co ułatwia transport,"},
            {punkt: "Kolor: Mr. Pink"}
        ],
        cena: "99,00 zł",
        rozmiary: ["S/M", "L/XL"],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/245033-44fce4.jpg",
        kategoriaId: 8,
        podkategoriaId: 17
    },
    {
        id: 245031,
        nazwa: "Czapka The North Face The Norm",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 60% bawełna, 40% poliester,"},
            {punkt: "Otwory wentylacyjne na panelach,"},
            {punkt: "Wysokiej jakości haft z logiem na przednim panelu czapki,"},
            {punkt: "Czapka typu: snapback,"},
            {punkt: "Kolor: Wild Aster"},
            {punkt: "Kod: NF0A3SH3ZDN1"}
        ],
        cena: "89,00 zł",
        rozmiary: [],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/245031-714193.jpg",
        kategoriaId: 8,
        podkategoriaId: 18
    },
    {
        id: 245030,
        nazwa: "Czapka The North Face The Norm",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 60% bawełna, 40% poliester,"},
            {punkt: "Otwory wentylacyjne na panelach,"},
            {punkt: "Wysokiej jakości haft z logiem na przednim panelu czapki,"},
            {punkt: "Czapka typu: snapback,"},
            {punkt: "Kolor: Pink"},
            {punkt: "Kod: NF0A3SH3ZDN1"}
        ],
        cena: "89,00 zł",
        rozmiary: [],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/245030-35cbd1.jpg",
        kategoriaId: 8,
        podkategoriaId: 18
    },
    {
        id: 245021,
        nazwa: "Kapelusz Kamuflage Mesh",
        opis: '',
        opisPunkty: [
            {punkt: "Wykonanie: 100% bawełna,"},
            {punkt: "Klasyczny kształt,"},
            {punkt: "Nadruk na przodzie"},
            {punkt: "Siateczkowe wykończenie kapelusza,"},
            {punkt: "Kolor: Biały"}
        ],
        cena: "99,00 zł",
        rozmiary: [],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/245021-7d82c7.jpg",
        kategoriaId: 8,
        podkategoriaId: 17
    },
    {
        id: 242866,
        nazwa: "Czapka Zimowa Jimmy Jinx JJ",
        opis: '',
        opisPunkty: [
            {punkt: "Skład: 100% akryl,"},
            {punkt: "Miękka i przyjemna w dotyku,"},
            {punkt: "Dwuwarstwowa,"},
            {punkt: "Kolor: Grey"},
            {punkt: "Naszywka na przodzie,"},
            {punkt: "Ciepła i praktyczna w użytkowaniu."}
        ],
        cena: "69,00 zł",
        rozmiary: [],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/022020/242866-f6b4e4.jpg",
        kategoriaId: 8,
        podkategoriaId: 19
    },
    {
        id: 221743,
        nazwa: "Chest Rig Kamuflage Candy",
        opis: '',
        opisPunkty: [
            {punkt: "Chest rig Kamuflage,"},
            {punkt: "Saszetka na pierś w formie kamizelki."},
            {punkt: "Wykonana z poliestru wysokiej jakości."},
            {punkt: "Na przodzie otwarta kieszonka z siatki,"},
            {punkt: "Zawieszka na klucze oraz dwie kieszonki na akcesoria, zamykane na zamek,"},
            {punkt: "Po wewnętrznej stronie żakardowa metka,"},
            {punkt: "Regulowane szelki,"},
            {punkt: "Przegrody zamykane na zamki YKK."},
            {punkt: "Na przodzie wysokiej jakości haft z logo,"},
            {punkt: "Kolor: czarny,"},
            {punkt: "Najnowsza kolekcja!"}
        ],
        cena: "139,00 zł",
        rozmiary: [],
        bestseller: true,
        obrazek: "https://csts3.quartic.com.pl/e8a2d2ff4a3b47e2/e1-c0/230x345/aHR0cDovL3NlbGVjdHNob3AucGwvbW9k/cHViL19yc2VsZWN0c2hvcC9wcm9kdWN0/L3NtYWxsLzEyMjAxOC8yMjE3NDMtMDI0/NDU5LmpwZw==.jpg",
        kategoriaId: 9,
        podkategoriaId: 20
    },
    {
        id: 221742,
        nazwa: "Chest Rig Kamuflage Flash",
        opis: '',
        opisPunkty: [
            {punkt: "Chest rig Kamuflage,"},
            {punkt: "Saszetka na pierś w formie kamizelki."},
            {punkt: "Wykonana z poliestru wysokiej jakości."},
            {punkt: "Na przodzie otwarta kieszonka z siatki,"},
            {punkt: "Zawieszka na klucze oraz dwie kieszonki na akcesoria, zamykane na zamek,"},
            {punkt: "Po wewnętrznej stronie żakardowa metka,"},
            {punkt: "Regulowane szelki,"},
            {punkt: "Przegrody zamykane na zamki YKK."},
            {punkt: "Na przodzie wysokiej jakości haft z logo,"},
            {punkt: "Odblaskowe, haftowane logo!"},
            {punkt: "Kolor: czarny,"},
            {punkt: "Najnowsza kolekcja!"}
        ],
        cena: "149,00 zł",
        rozmiary: [],
        bestseller: true,
        obrazek: "https://csts3.quartic.com.pl/e8a2d2ff4a3b47e2/e1-c0/230x345/aHR0cDovL3NlbGVjdHNob3AucGwvbW9k/cHViL19yc2VsZWN0c2hvcC9wcm9kdWN0/L3NtYWxsLzEyMjAxOC8yMjE3NDItZjkw/ODQ5LmpwZw==.jpg",
        kategoriaId: 9,
        podkategoriaId: 20
    },
    {
        id: 244661,
        nazwa: "Torba Ripndip Sliced",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 100% bawełna,"},
            {punkt: "Wyraziste nadruki na obu stronach,"},
            {punkt: "Idealna na zakupy i nie tylko,"},
            {punkt: "Wymiary: 38cm x 36cm,"},
            {punkt: "Bardzo trwała i solidnie wykonana"},
            {punkt: "Kod: RND4221"}
        ],
        cena: "69,00 zł",
        rozmiary: [],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244661-6a326f.jpg",
        kategoriaId: 9,
        podkategoriaId: 21
    },
    {
        id: 244190,
        nazwa: "Saszetka Ellesse Selva",
        opis: '',
        opisPunkty: [
            {punkt: "Saszetka marki Ellesse,"},
            {punkt: "Z przodu nadruk,"},
            {punkt: "Jedna duża komora zamykana na zamek, druga na przodzie również zamykana na zamek,"},
            {punkt: "Plastikowa regulacja paska,"},
            {punkt: "Wysoka jakość wykonania,"},
            {punkt: "Kolor:Red Navy"},
            {punkt: "Kod: SAEA1368NAVY"},
            {punkt: "Najnowsza kolekcja!"}
        ],
        cena: "59,00 zł",
        rozmiary: [],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244190-831d11.jpg",
        kategoriaId: 9,
        podkategoriaId: 22
    },
    {
        id: 244180,
        nazwa: "Torebka Ellesse Templeton",
        opis: '',
        opisPunkty: [
            {punkt: "Torebka  na ramię marki Ellesse,"},
            {punkt: "Z przodu nadruk,"},
            {punkt: "Jedna duża komora i mniejsza na przodzie,"},
            {punkt: "Rozmiary: 13,5cm x 18cm,"},
            {punkt: "Plastikowa regulacja paska,"},
            {punkt: "Wysoka jakość wykonania,"},
            {punkt: "Kolor: Khaki"},
            {punkt: "Kod: SAAY0709"},
            {punkt: "Najnowsza kolekcja!"}
        ],
        cena: "59,00 zł",
        rozmiary: [],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244180-4b4561.jpg",
        kategoriaId: 9,
        podkategoriaId: 21
    },
    {
        id: 245037,
        nazwa: "Maska Kamuflage Too Many Logos",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 100% bawełna"},
            {punkt: "Kolor: Czarny"},
            {punkt: "Nadruki na przodzie,"},
            {punkt: "Dopasowana do twarzy,"},
            {punkt: "Wygodna dla uszu,"}
        ],
        cena: "29,00 zł",
        rozmiary: ["M/L", "XS/S"],
        bestseller: true,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/042020/245037-20328b.jpg",
        kategoriaId: 10,
        podkategoriaId: 23
    },
    {
        id: 244658,
        nazwa: "Przypinka Ripndip Hash Bros",
        opis: '',
        opisPunkty: [
            {punkt: "Pin Ripndip,"},
            {punkt: "Metalowy,"},
            {punkt: "Podwójne mocowanie."},
            {punkt: "Kod: RND4214"}
        ],
        cena: "59,00 zł",
        rozmiary: [],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244658-d6f5bf.jpg",
        kategoriaId: 10,
        podkategoriaId: 24
    },
    {
        id: 244646,
        nazwa: "Skarpety Ripndip Lord Nermal",
        opis: '',
        opisPunkty: [
            {punkt: "Materiał: 70% bawełna, 27% poliester, 3% spandex,"},
            {punkt: "Kolor: Gray Speckle"},
            {punkt: "Rozmiar: unisex,"},
            {punkt: "Dodatkowe wsparcie wokół pięty,"},
            {punkt: "Skarpetki bezszwowe, bardzo przewiewne,"},
            {punkt: "Bardzo wygodne skarpetki,"},
            {punkt: "Miękka wyściółka stopy,"},
            {punkt: "Bardzo wysoka jakość."},
            {punkt: "Kod: RND4201"}
        ],
        cena: "59,00 zł",
        rozmiary: [],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244646-8eafb8.jpg",
        kategoriaId: 10,
        podkategoriaId: 25
    },
    {
        id: 244033,
        nazwa: "Pasek Kamuflage",
        opis: '',
        opisPunkty: [
            {punkt: "Długość ok (z klamrą): 126 cm,"},
            {punkt: "Szerokość: 4 cm,"},
            {punkt: "Kolor: szary"},
            {punkt: "Metalowa klamra,"},
            {punkt: "Pasek parciany,"},
            {punkt: "Haftowane logo na zakończeniu paska"},
            {punkt: "Metalowe zakończenie na zacisk"}
        ],
        cena: "39,00 zł",
        rozmiary: [],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/032020/244033-dda4d3.jpg",
        kategoriaId: 10,
        podkategoriaId: 26
    },
    {
        id: 242259,
        nazwa: "Okulary Vans As If",
        opis: '',
        opisPunkty: [
            {punkt: "Oprawka: 90% miedzionikiel, 10% poliwęglan, soczewki: 100% poliwęglan"},
            {punkt: "Filtr: UV400,"},
            {punkt: "Szerokość oprawek 15cm,"},
            {punkt: "Wysokość oprawek: 5cm,"},
            {punkt: "Kolor: Matte Black-Blue Mirror"},
            {punkt: "Najnowsza kolekcja!"},
            {punkt: "Rozmiar: Uniwersalny,"},
            {punkt: "Kod: VN0A4DT1VB0"}
        ],
        cena: "79,00 zł",
        rozmiary: [],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/022020/242259-1f21ba.jpg",
        kategoriaId: 10,
        podkategoriaId: 27
    },
    {
        id: 168387,
        nazwa: "Zegarek Cheapo Khordshid",
        opis: '',
        opisPunkty: [
            {punkt: "Typ: zegarek męski "},
            {punkt: "Mechanizm: japoński, kwarcowy, analogowy"},
            {punkt: "Tarcza: biała"},
            {punkt: "Szkło: mineralne"},
            {punkt: "Koperta: stalowa, w kolorze srebrnym"},
            {punkt: "Średnica koperty: 40 mm"},
            {punkt: "Pasek: granatowy, nylonowy"},
            {punkt: "Wodoodporność: nie"}
        ],
        cena: "159,00 zł",
        rozmiary: [],
        bestseller: false,
        obrazek: "https://selectshop.pl/modpub/_rselectshop/product/small/052016/168387-3b81ef.jpg",
        kategoriaId: 10,
        podkategoriaId: 28
    }
]